MACRO(HLATestSuite_ADD_TEST TESTNAME FEDFILE TEST_FILES_LIST)        
    ADD_EXECUTABLE(${TESTNAME} ${TEST_FILES_LIST})
    
    TARGET_LINK_LIBRARIES (${TESTNAME} ${CERTI_LIBRARIES})
    
    INSTALL(TARGETS ${TESTNAME} 
            RUNTIME DESTINATION bin)
    INSTALL(FILES ${FEDFILE}
            DESTINATION share/federations)
ENDMACRO(TestSuite_ADDTEST TESTNAME TEST_FILES_LIST)
