#ifndef CERTI_RTI1516_RETURN_CODES_H
#define CERTI_RTI1516_RETURN_CODES_H

namespace certi {
	namespace rti1516_test {

		enum ReturnCode {
			RETURN_NO_ERRORS = 0,
			RETURN_ERROR_CREATING_AMBASSADOR,
			RETURN_ERROR_CREATING_FEDERATION,
			RETURN_ERROR_JOINING_INVALID_FEDERATION ,
			RETURN_ERROR_JOINING_VALID_FEDERATION,
			RETURN_ERROR_PUBLISHING_INTERACTIONS,
			RETURN_ERROR_DESTROYING_FEDERATION,
			RETURN_ERROR_RESIGNING_FEDERATION,
			RETURN_ERROR_GET_CLASS_HANDLE,
			RETURN_ERROR_GET_CLASS_NAME,
			RETURN_ERROR_GET_ATTRIBUTE_HANDLE,
			RETURN_ERROR_GET_ATTRIBUTE_NAME,
			RETURN_ERROR_GET_INTERACTION_HANDLE,
			RETURN_ERROR_GET_INTERACTION_NAME,
			RETURN_ERROR_GET_PARAMETER_HANDLE,
			RETURN_ERROR_GET_PARAMETER_NAME,
			RETURN_ERROR_GET_OBJECT_HANDLE,
			RETURN_ERROR_GET_OBJECT_NAME,
			RETURN_ERROR_PUBLISH_CLASS_ATTRIBUTES,
			RETURN_ERROR_UNPUBLISH_CLASS,
			RETURN_ERROR_UNPUBLISH_CLASS_ATTRIBUTES,
			RETURN_ERROR_PUBLISH_INTERACTION,
			RETURN_ERROR_UNPUBLISH_INTERACTION,
			RETURN_ERROR_SUBSCRIBE_CLASS_ATTRIBUTES,
			RETURN_ERROR_UNSUBSCRIBE_CLASS,
			RETURN_ERROR_UNSUBSCRIBE_CLASS_ATTRIBUTES,
			RETURN_ERROR_SUBSCRIBE_INTERACTION,
			RETURN_ERROR_UNSUBSCRIBE_INTERACTION,
			RETURN_UNDEFINED_ERROR,

		};

	}
}




#endif // CERTI_RTI1516_RETURN_CODES_H
